In [56]:
import numpy as np

In [57]:
list1 = [1, 2, 3, 4]

In [58]:
array1 = np.array(list1)

In [59]:
array1

array([1, 2, 3, 4])

In [60]:
list2 = [90, 98, 78, 66]

In [61]:
array2 = np.array(list2)

In [62]:
array2

array([90, 98, 78, 66])

In [63]:
my_lists = [list1, list2]

In [64]:
my_lists

[[1, 2, 3, 4], [90, 98, 78, 66]]

In [65]:
array3 = np.array(my_lists)

In [66]:
array3

array([[ 1,  2,  3,  4],
       [90, 98, 78, 66]])

In [67]:
array3.dtype

dtype('int64')

In [68]:
array3.shape

(2, 4)

In [69]:
zeros1 = np.zeros((10, 2))

In [70]:
zeros1.dtype

dtype('float64')

In [71]:
zeros1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
empty1 = np.empty([1, 2])

In [73]:
empty1

array([[5.73021895e-300, 3.10503618e+231]])

In [74]:
ones1 = np.ones(shape=(4, 5), dtype=int)

In [75]:
ones1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
ones1.dtype

dtype('int64')

In [77]:
ones1.shape

(4, 5)

In [78]:
id1 = np.eye(5, dtype=int)

In [79]:
id1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [80]:
!pwd

/Users/surendra/workspaces/python-remote-workspace/notebooks/numpy


In [81]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [82]:
np.arange(5, 50, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [83]:
np.arange(5, 36, 4, dtype=int)

array([ 5,  9, 13, 17, 21, 25, 29, 33])

### Some arthematic operations

In [85]:
array3

array([[ 1,  2,  3,  4],
       [90, 98, 78, 66]])

In [86]:
array3 * 10

array([[ 10,  20,  30,  40],
       [900, 980, 780, 660]])

In [87]:
array3 /10

array([[0.1, 0.2, 0.3, 0.4],
       [9. , 9.8, 7.8, 6.6]])

In [88]:
array3 + array3

array([[  2,   4,   6,   8],
       [180, 196, 156, 132]])

In [89]:
# not a matrix multiplication 
# just muliplies xorrsponding number like addition and subtraction
array3 * array3

array([[   1,    4,    9,   16],
       [8100, 9604, 6084, 4356]])

In [90]:
array3 / array3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])