In [1]:
import numpy as np

In [6]:
a1 = np.arange(0, 20)

In [7]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
a1[3]

3

In [9]:
a1[6:10]

array([6, 7, 8, 9])

In [10]:
a1[15:20] = -99

In [11]:
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, -99, -99, -99, -99, -99])

In [12]:
a2 = np.arange(0, 11)

In [13]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a2_slice = a2[0:5]

In [15]:
a2_slice

array([0, 1, 2, 3, 4])

In [16]:
# change all elements in slice
a2_slice[:] = -1

In [17]:
a2_slice

array([-1, -1, -1, -1, -1])

In [19]:
# all operations performed on np.array effects the original array
a2

array([-1, -1, -1, -1, -1,  5,  6,  7,  8,  9, 10])

In [ ]:
# to avoid this 